# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 820c5a5225f0b3021d930fb562de7546a8bf1e6c6af7592f45eaf39768f7f64f164a3f4ec296f92349423722f66616709f9d41e0e1b6ef35abe01f609f4a6b4c

test:
  secret_key_base: de1b027d8d7235de39559a5d2d00af19a07e772214f86ddacb01cf9f90d0287c470e8bd7a10e76c45eb2fcdc2a5d33cdf20899dfef16e2bc8700f02f0c30e161

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
